version: '3'

services:
  pastelaria-app:
    build: .
    container_name: doc-pastelaria
    depends_on:
      - database-app
      - redis-app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d
    networks:
      app-network:
        ipv4_address: 172.29.5.4

  database-app:
    image: mysql:8.0.19
    container_name: pastelaria-db
    volumes:
    - ./dbdata:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: doc88
      MYSQL_ROOT_PASSWORD: q1w2e3r4
      MYSQL_USER: pastelaria
      MYSQL_PASSWORD: q1w2e3r4
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      app-network:
        ipv4_address: 172.29.5.5

  redis-app:
    image: redis:5.0
    container_name: redis-app
    networks:
      app-network:
        ipv4_address: 172.29.5.6

networks:
  app-network:
    ipam:
      config:
        - subnet: 172.29.5.0/16
